- name: "Setup system basics."
  hosts: localhost
  connection: local
  tasks:
    - name: apt - install basic apps
      become: yes
      apt:
        name:
          # terminal
          - vim
          - tmux
          - tig
          - curl
          - htop
          - mc
          - moc
          # networking
          - net-tools
          - nmap
          # desktop apps
          - deja-dup
          - thunderbird
          - gimp
          - calibre
          - vlc
          - gnome-shell-pomodoro
        state: present

    - name: .bashrc - create symlink
      file:
        src: "{{ playbook_dir }}/config/.bashrc"
        dest: ~/.bashrc
        state: link
        force: true

    # setup flatpak
    - name: flatpak - install dependencies
      become: yes
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: present
    - name: flatpak - add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak:
        name:
          - org.keepassxc.KeePassXC
          - com.github.tchx84.Flatseal # flatpak rights management
          - io.gitlab.librewolf-community
          - com.github.micahflee.torbrowser-launcher
          - org.signal.Signal
          - hu.irl.cameractrls # webcam settings
          - com.transmissionbt.Transmission
        state: present

    # install and configure newsboat RSS reader
    - name: newsboat - install
      become: yes
      apt:
        name: newsboat
        state: present
    - name: newsboat - create config dir
      file:
        path: ~/.newsboat/
        state: directory
    - name: newsboat - create symlink for config file
      file:
        src: "{{ playbook_dir }}/config/newsboat/config"
        dest: ~/.newsboat/config
        state: link
        force: true
    - name: newsboat - create symlink for urls file
      file:
        src: "{{ playbook_dir }}/config/newsboat/urls"
        dest: ~/.newsboat/urls
        state: link
        force: true
    - name: cron - schedule newsboard reload
      cron:
        name: "schedule newsboat reload"
        minute: "*/15"
        job: newsboat --execute=reload --log-level=1 --log-file=~/tmp/newsboat.log

    # install element
    - name: element - install dependencies
      become: yes
      apt:
        name:
          - wget
          - apt-transport-https
        state: present
    - name: element - add element repository key
      become: yes
      apt_key:
        id: 12D4CD600C2240A9F4A82071D7B0B66941D01538
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        keyring: /usr/share/keyrings/element-io-archive-keyring.gpg
    - name: element - add element repository
      become: yes
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main"
        state: present
        filename: "element-io"
    - name: element - install element desktop
      become: yes
      apt:
        name: element-desktop
        state: present

    # install indicator-sound-switcher
    - name: indicator-sound-switcher - add PPA
      become: yes
      apt_repository:
        repo: "ppa:yktooo/ppa"
        state: present
    - name: indicator-sound-switcher - install
      become: yes
      apt:
        name: indicator-sound-switcher
        state: present

    # install brave from PPA
    - name: brave - add release key
      become: yes
      apt_key:
        id: D8BAD4DE7EE17AF52A834B2D0BB75829C2D4E821
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    - name: brave - add PPA
      become: yes
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    - name: brave - install
      become: yes
      apt:
        name: brave-browser
        state: present
