- name: "Setup system basics."
  hosts: localhost
  connection: local
  tasks:
    # install apt packages
    - name: apt - update
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 3600 # caching time: 1 hour
      become: yes
    - name: apt - install basic apps
      apt:
        name:
          # terminal
          - vim
          - tmux
          - tig
          - curl
          - htop
          - mc
          - moc
          # networking
          - net-tools
          - nmap
          # desktop apps
          - deja-dup
          - thunderbird
          - gimp
          - calibre
        state: latest
      become: yes

    # setup flatpak
    - name: flatpak - install dependencies
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
      become: yes
    - name: flatpak - add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak:
        name:
          - org.keepassxc.KeePassXC
          - org.videolan.VLC
          - com.github.tchx84.Flatseal # flatpak rights management
          - io.gitlab.librewolf-community
          - com.jgraph.drawio.desktop
          - im.riot.Riot
          - org.signal.Signal
          - com.brave.Browser
          - com.microsoft.Edge
        state: present

    # install and configure newsboat RSS reader
    - name: newsboat - install
      apt:
        name:
          - newsboat
        state: latest
      become: yes
    - name: newsboat - create config folder
      file:
        path: ~/.newsboat/
        state: directory
    - name: newsboat - set urls
      copy:
        src: config/newsboat/urls
        dest: ~/.newsboat/urls
    - name: newsboat - set config
      copy:
        src: config/newsboat/config
        dest: ~/.newsboat/config

    # schedule newsboat reload
    - name: cron - schedule newsboard reload
      ansible.builtin.cron:
        name: "schedule newsboat reload"
        minute: "*/15"
        job: newsboat --execute=reload --log-level=1 --log-file=~/tmp/newsboat.log
