- name: "Setup system basics."
  hosts: localhost
  connection: local
  tasks:
    # install apt utils
    - name: apt - update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600 # caching time: 1 hour
    - name: apt - install utils
      apt:
        name:
          - vim
          - git
          - docker.io
          - docker-compose
          - thunderbird
          - torbrowser-launcher
          - apt-transport-https
          - curl
          - gnome-shell-extensions
        state: latest

    # install brave browser
    - name: brave - download signing key
      shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    - name: brave - add ppa repository
      shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
    - name: brave - apt update
      apt:
        update_cache: yes
    - name: brave - install
      apt:
        name:
          - brave-browser
        state: latest

    # install sound-switcher
    - name: snap - install indicator-sound-switcher
      snap:
        name: indicator-sound-switcher

    # install firefox
    - name: firefox - install
      apt:
        name:
          - firefox
        state: latest

    # setup flatpak
    - name: flatpak - install dependencies
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
    - name: flatpak - add flathub repository
      shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks: keepass, vlc
    - name: flatpak - get installed flatpaks
      shell: flatpak list
      register: flatpak_list
    - name: flatpak - install keepass
      shell: flatpak install -y flathub org.keepassxc.KeePassXC
      when: flatpak_list.stdout.find("org.keepassxc.KeePassXC") == -1
    - name: flatpak - install vlc
      shell: flatpak install -y flathub org.videolan.VLC
      when: flatpak_list.stdout.find("org.videolan.VLC") == -1
