- name: "Setup system basics."
  hosts: localhost
  connection: local
  tasks:
    # install apt packages
    - name: apt - update
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 3600 # caching time: 1 hour
      become: yes
    - name: apt - install utils
      apt:
        name:
          # terminal
          - vim
          - tmux
          - tig
          - curl
          - htop
          - mc
          # networking
          - net-tools
          - nmap
          # desktop apps
          - thunderbird
          - gimp
          # gnome
          # OPTIONAL: move to appearance.yaml
          - gnome-shell-extensions
          - gnome-tweaks
          - gnome-shell-extension-appindicator
          # development
          # OPTIONAL: move to development.yaml
          - git
          - docker.io
          - docker-compose
        state: latest
      become: yes

    # setup flatpak
    - name: flatpak - install dependencies
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
      become: yes
    - name: flatpak - add flathub repository
      # OPTIONAL: add repo with flatpak command
      shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak:
        name:
          - org.keepassxc.KeePassXC
          - org.videolan.VLC
          - com.github.tchx84.Flatseal # flatpak rights management
          - io.gitlab.librewolf-community
          - com.jgraph.drawio.desktop
          - im.riot.Riot
          - org.signal.Signal
          - com.brave.Browser
        state: present
