- name: "Setup system basics."
  hosts: localhost
  connection: local
  tasks:
    - name: apt - install basic apps
      become: yes
      apt:
        name:
          # terminal
          - vim
          - tmux
          - tig
          - curl
          - htop
          - mc
          - moc
          # networking
          - net-tools
          - nmap
          # desktop apps
          - deja-dup
          - thunderbird
          - gimp
          - calibre
          - vlc
          - gnome-shell-pomodoro
        state: present

    # setup flatpak
    - name: flatpak - install dependencies
      become: yes
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: present
    - name: flatpak - add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak:
        name:
          - org.keepassxc.KeePassXC
          - com.github.tchx84.Flatseal # flatpak rights management
          - io.gitlab.librewolf-community
          - com.jgraph.drawio.desktop
          - org.signal.Signal
          - com.brave.Browser
          - com.microsoft.Edge
          - hu.irl.cameractrls # webcam settings
          - com.transmissionbt.Transmission
          - com.spotify.Client
        state: present

    # install and configure newsboat RSS reader
    - name: newsboat - install
      become: yes
      apt:
        name: newsboat
        state: present
    - name: newsboat - copy config files
      copy:
        src: config/newsboat/
        dest: ~/.newsboat/
    - name: cron - schedule newsboard reload
      ansible.builtin.cron:
        name: "schedule newsboat reload"
        minute: "*/15"
        job: newsboat --execute=reload --log-level=1 --log-file=~/tmp/newsboat.log

    # install element
    - name: element - install dependencies
      become: yes
      apt:
        name:
          - wget
          - apt-transport-https
        state: present
    - name: element - add element repository key
      become: yes
      apt_key:
        id: 12D4CD600C2240A9F4A82071D7B0B66941D01538
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        keyring: /usr/share/keyrings/element-io-archive-keyring.gpg
    - name: element - add element repository
      become: yes
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main"
        state: present
        filename: "element-io"
    - name: element - install element desktop
      become: yes
      apt:
        name: element-desktop
        state: present
        update_cache: yes

    # install indicator-sound-switcher
    - name: indicator-sound-switcher - add PPA
      become: yes
      apt_repository:
        repo: "ppa:yktooo/ppa"
        state: present
    - name: indicator-sound-switcher - install
      become: yes
      apt:
        name: indicator-sound-switcher
        state: present

    # install syncthing from PPA
    - name: syncthing - import release key
      become: yes
      apt_key:
        id: 37C84554E7E0A261E4F76E1ED26E6ED000654A3E
        url: https://syncthing.net/release-key.gpg
        keyring: /usr/share/keyrings/syncthing-archive-keyring.gpg  
    - name: syncthing - add PPA
      become: yes
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
    - name: syncthing - install element desktop
      become: yes
      apt:
        name: syncthing
        state: present
