- name: "Setup system basics."
  hosts: localhost
  connection: local
  tasks:
    # install apt packages
    - name: apt - update
      become: yes
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 3600 # caching time: 1 hour
    - name: apt - install basic apps
      become: yes
      apt:
        name:
          # terminal
          - vim
          - tmux
          - tig
          - curl
          - htop
          - mc
          - moc
          # networking
          - net-tools
          - nmap
          # desktop apps
          - deja-dup
          - thunderbird
          - gimp
          - calibre
          - vlc
        state: latest

    # setup flatpak
    - name: flatpak - install dependencies
      become: yes
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
    - name: flatpak - add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak:
        name:
          - org.keepassxc.KeePassXC
          - com.github.tchx84.Flatseal # flatpak rights management
          - io.gitlab.librewolf-community
          - com.jgraph.drawio.desktop
          - org.signal.Signal
          - com.brave.Browser
          - com.microsoft.Edge
          - hu.irl.cameractrls # webcam settings
        state: present

    # install and configure newsboat RSS reader
    - name: newsboat - install
      become: yes
      apt:
        name:
          - newsboat
        state: latest
    - name: newsboat - create config folder
      file:
        path: ~/.newsboat/
        state: directory
    - name: newsboat - set urls
      copy:
        src: config/newsboat/urls
        dest: ~/.newsboat/urls
    - name: newsboat - set config
      copy:
        src: config/newsboat/config
        dest: ~/.newsboat/config

    # schedule newsboat reload
    - name: cron - schedule newsboard reload
      ansible.builtin.cron:
        name: "schedule newsboat reload"
        minute: "*/15"
        job: newsboat --execute=reload --log-level=1 --log-file=~/tmp/newsboat.log

    # install element
    - name: element - install dependencies
      become: yes
      apt:
        name:
          - wget
          - apt-transport-https
        state: present
    - name: element - add element repository key
      become: yes
      apt_key:
        # TODO: add key id
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        keyring: /usr/share/keyrings/element-io-archive-keyring.gpg
        state: present
    - name: element - add element repository
      become: yes
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main'
        state: present
        filename: 'element-io'
    - name: element - install element desktop
      become: yes
      apt:
        name: element-desktop
        state: present
        update_cache: yes
