- name: "Setup company software."
  hosts: localhost
  connection: local
  tasks:
    # setup flatpak
    - name: flatpak - install dependencies
      become: yes
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: present
    - name: flatpak - add flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak:
        name:
          - us.zoom.Zoom
          - com.slack.Slack

    # chrome
    - name: chrome - add repository
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
        state: present
    - name: Install Google Chrome
      become: yes
      apt:
        name: google-chrome-stable
        state: present
