- name: "Setup company software."
  hosts: localhost
  connection: local
  tasks:

    # setup flatpak
    - name: flatpak - install dependencies
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
      become: yes
    - name: flatpak - add flathub repository
      shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks: slack, zoom
    - name: flatpak - get installed flatpaks
      shell: flatpak list
      register: flatpak_list
    - name: flatpak - install slack
      shell: flatpak install -y flathub com.slack.Slack
      when: flatpak_list.stdout.find("com.slack.Slack") == -1
    - name: flatpak - install zoom
      shell: flatpak install -y flathub us.zoom.Zoom
      when: flatpak_list.stdout.find("us.zoom.Zoom") == -1
    - name: flatpak - install JabRef
      shell: flatpak install -y flathub org.jabref.jabref
      when: flatpak_list.stdout.find("org.jabref.jabref") == -1

    # install snap packages: miro
    - name: snap - install snap
      apt:
        name:
          - snapd
        state: latest
      become: yes
    - name: snap - install miro
      snap:
        name: miro
      become: yes
