- name: "Setup company software."
  hosts: localhost
  connection: local
  tasks:

    # setup flatpak
    - name: flatpak - install dependencies
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
      become: yes
    - name: flatpak - add flathub repository
      shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    # install flatpaks
    - name: flatpaks - install
      community.general.flatpak: 
        name: 
          - com.slack.Slack
          - us.zoom.Zoom
          - org.jabref.jabref  # literature management
        state: present

    # install snap packages: miro
    - name: snap - install snap
      apt:
        name:
          - snapd
        state: latest
      become: yes
    - name: snap - install miro
      snap:
        name: miro
      become: yes
