- name: "Setup development tools."
  hosts: localhost
  connection: local
  tasks:
    # apt
    - name: apt - update
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 3600 # caching time: 1 hour
      become: yes
    - name: apt - install dev tools
      apt:
        name:
          - pipx
        state: latest
      become: yes

    # install pyenv (and python build dependencies)
    - name: pyenv - install
      shell: |
        which pyenv || curl https://pyenv.run | bash
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo '# pyenv configuration' >> ~/.bashrc
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo 'eval "$(pyenv init -)"' >> ~/.bashrc
    - name: apt - install python build dependencies
      apt:
        name:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: latest
      become: yes

    # install poetry
    - name: poetry - install
      shell: |
        which poetry || curl -sSL https://install.python-poetry.org | python3 -

    # configure fish shell
    - name: fish - install
      apt:
        name:
          - fish
        state: latest
      become: yes
    - name: fish - create config folder
      file:
        path: ~/.config/fish
        state: directory
    - name: fish - write config file
      copy:
        src: config/config.fish
        dest: ~/.config/fish/config.fish

    # configure newsboat RSS reader
    - name: newsboat - install
      apt:
        name:
          - newsboat
        state: latest
      become: yes
    - name: newsboat - create config folder
      file:
        path: ~/.newsboat/
        state: directory
    - name: newsboat - set urls
      copy:
        src: config/newsboat/urls
        dest: ~/.newsboat/urls
    - name: newsboat - set config
      copy:
        src: config/newsboat/config
        dest: ~/.newsboat/config

    # schedule git fetch
    - name: cron - schedule newsboard reload
      ansible.builtin.cron:
        name: "schedule newsboat reload"
        minute: "*/15"
        job: newsboat --execute=reload --log-level=1 --log-file=~/tmp/newsboat.log

    # install vscodium
    - name: vscodium - add the GPG key of the repository
      shell: |
        wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
        | gpg --dearmor \
        | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
    - name: vscodium - add ppa repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg arch=amd64] https://download.vscodium.com/debs vscodium main" \
        | sudo tee /etc/apt/sources.list.d/vscodium.list
      become: yes
    - name: vscodium - apt update
      apt:
        upgrade: no
        update_cache: yes
      become: yes
    - name: vscodium - apt install
      apt:
        name:
          - codium
        state: latest
      become: yes
