- name: "Setup development tools."
  hosts: localhost
  connection: local
  tasks:
    # apt
    - name: apt - update
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600  # caching time: 1 hour
    - name: apt - install dev tools
      become: yes
      apt:
        name:
          - git
          - pipx
          - docker.io
          - docker-compose
        state: latest

    # install pyenv (and python build dependencies)
    # OPTIONAL: use blockinfile module
    - name: pyenv - install
      shell: |
        which pyenv || curl https://pyenv.run | bash
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo '# pyenv configuration' >> ~/.bashrc
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
        grep -qxF 'eval "$(pyenv init -)"' ~/.bashrc || echo 'eval "$(pyenv init -)"' >> ~/.bashrc
    - name: apt - install python build dependencies
      become: yes
      apt:
        name:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: latest

    # install poetry
    # OPTIONAL: try installing with pipx instead
    - name: poetry - install
      shell: |
        which poetry || curl -sSL https://install.python-poetry.org | python3 -

    # configure fish shell
    - name: fish - install
      become: yes
      apt:
        name: fish
        state: latest
    - name: fish - create config folder
      file:
        path: ~/.config/fish
        state: directory
    - name: fish - write config file
      copy:
        src: config/config.fish
        dest: ~/.config/fish/config.fish

    # install vscode
    - name: vscode - install snapd
      become: yes
      apt:
        name: snapd
        state: latest
    - name: vscode - install with snap
      become: yes
      snap:
        name: code
        classic: yes

    # install vscodium
    - name: vscodium - add release key
      become: yes
      apt_key:
        id: 1302DE60231889FE1EBACADC54678CF75A278D9C
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        keyring: /usr/share/keyrings/vscodium-archive-keyring.gpg
    - name: vscodium - add repository
      become: yes
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg arch=amd64] https://download.vscodium.com/debs vscodium main
    - name: vscodium - apt install
      become: yes
      apt:
        name: codium
