- name: "Setup development tools."
  hosts: localhost
  connection: local
  tasks:
    # apt tools
    - name: apt - install dev tools
      become: yes
      apt:
        name:
          - git
          - pipx
          - docker.io
          - docker-compose
          - snapd  # used to install vscode

    # install pyenv (and python build dependencies)
    # OPTIONAL: use blockinfile module
    - name: pyenv - check if installed
      command: which pyenv
      register: which_pyenv
      failed_when: false  # do not fail if does not exist
      changed_when: false  # do not report as change
    - name: pyenv - install
      shell: curl https://pyenv.run | bash
      when: which_pyenv.rc != 0  # run only if return code is not 0
    - name: pyenv - settings in .bashrc
      blockinfile: 
        path: ~/.bashrc
        block: |
          # pyenv configuration
          export PYENV_ROOT="$HOME/.pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
    - name: apt - install python build dependencies
      become: yes
      apt:
        name:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev

    # install poetry
    # OPTIONAL: try installing with pipx instead
    - name: poetry - install
      shell: |
        which poetry || curl -sSL https://install.python-poetry.org | python3 -

    # configure fish shell
    - name: fish - install
      become: yes
      apt:
        name: fish
    - name: fish - copy config file
      copy:
        src: config/fish/
        dest: ~/.config/fish/

    # install vscode
    - name: vscode - install with snap
      become: yes
      snap:
        name: code
        classic: yes

    # install vscodium
    - name: vscodium - add release key
      become: yes
      apt_key:
        id: 1302DE60231889FE1EBACADC54678CF75A278D9C
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        keyring: /usr/share/keyrings/vscodium-archive-keyring.gpg
    - name: vscodium - add repository
      become: yes
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg arch=amd64] https://download.vscodium.com/debs vscodium main
    - name: vscodium - apt install
      become: yes
      apt:
        name: codium
