- name: "Customize GNOME appearance."
  hosts: localhost
  connection: local
  tasks:
    - name: apt - install gnome tools
      apt:
        name:
          - gnome-shell-extensions
          - gnome-tweaks
          - gnome-shell-extension-appindicator
        state: present
      become: yes

    # gnome settings
    - name: dconf - 24h clock
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'24h'"
    - name: dconf - color scheme perfer-dark
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
    - name: dconf - disable animations
      community.general.dconf:
        key: "/org/gnome/desktop/interface/enable-animations"
        value: "false"
    - name: dconf - only apps from current workspace in app-switcher
      community.general.dconf:
        key: "/org/gnome/shell/app-switcher/current-workspace-only"
        value: "true"

    # keyboard shortcuts
    - name: dconf - launch and switch between dash items using Super+(0-9)
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/hot-keys"
        value: "true"
    - name: dconf - play/pause
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/play"
        value: "['<Super>F1']"
    - name: dconf - previous track
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/previous"
        value: "['<Super>F2']"
    - name: dconf - next track
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/next"
        value: "['<Super>F3']"
    - name: dconf - switch windows
      community.general.dconf:
        key: "/org/gnome/dektop/wm/keybindings/switch-windows"
        value: "['<Alt>Tab']"
    - name: dconf - switch windows backward
      community.general.dconf:
        key: "/org/gnome/dektop/wm/keybindings/switch-windows-backward"
        value: "['<Shift><Alt>Tab']"
