- name: "Customize GNOME appearance."
  hosts: localhost
  connection: local
  tasks:
    # install gnome tools
    - name: apt - update
      apt:
        upgrade: no
        update_cache: yes
        cache_valid_time: 3600 # caching time: 1 hour
      become: yes
    - name: apt - install gnome tools
      apt:
        name:
          - gnome-shell-extensions
          - gnome-tweaks
          - gnome-shell-extension-appindicator
        state: latest
      become: yes

    # gnome settings
    - name: gnome settings
      shell: |
        gsettings set org.gnome.desktop.interface color-scheme prefer-dark
        gsettings set org.gnome.desktop.interface enable-animations false
        gsettings set org.gnome.shell.app-switcher current-workspace-only true
