- name: "Customize GNOME appearance."
  hosts: localhost
  connection: local
  tasks:
    # gnome settings
    - name: gnome settings
      shell: |
        gsettings set org.gnome.desktop.interface color-scheme prefer-dark
        gsettings set org.gnome.desktop.interface enable-animations false
        gsettings set org.gnome.shell.app-switcher current-workspace-only true
