- name: "Setup local linux machine"
  hosts: localhost
  connection: local
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install apt-packages
      apt:
        name:
          - vim
          - git
          - docker.io
          - docker-compose
          - thunderbird
          - firefox
          - torbrowser-launcher
          - nextcloud-desktop
          - keepassxc
        state: present

    - name: Install vscode
      snap:
        name: code
        classic: yes

    # install signal-desktop
    - name: Download signing key for signal-desktop
      get_url:
        url: https://updates.signal.org/desktop/apt/keys.asc
        dest: /tmp/keys.asc
        checksum: sha256:2aca20b81a56ba0fbe24bdf58a45023e58a38392d885068afe596785ccd95491
    - name: Import signing key
      shell: |
        cat /tmp/keys.asc | gpg --dearmor > /tmp/signal-desktop-keyring.gpg
        cat /tmp/signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
    - name: Add repository into sources list
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
        state: present
        update_cache: yes
    - name: Install signal-desktop
      apt:
        name: signal-desktop
        state: present

    # install element-desktop
    - name: Install element dependencies
      apt:
        name:
          - wget
          - apt-transport-https
        state: present
    - name: Download signing key for Element
      get_url:
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        dest: /usr/share/keyrings/element-io-archive-keyring.gpg
        checksum: sha256:fbf7823608964237024b043b607415b75d7c64221ac98ff5b5e67941f24684c2
    - name: Add repository into sources list
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main
        state: present
        update_cache: yes
    - name: Install element-desktop
      apt:
        name: element-desktop

    # install VPN
    - name: mullvad - download deb package
      get_url:
        url: https://mullvad.net/download/app/deb/latest
        dest: /tmp/mullvad-latest.deb
        checksum: sha256:87f73868f1fa1364f36d71913a92c9805f6e1d8723bca896e6ea48a1ba4933da
      tags: 
        - vpn
    - name: mullvad - install with apt
      apt:
        deb: /tmp/mullvad-latest.deb
      tags: 
        - vpn
