- name: "Privacy settings."
  hosts: localhost
  connection: local
  tasks:
    # install syncthings
    - name: apt - install syncthing
      apt:
        name:
          - syncthing
        state: latest
      become: yes

    # install VPN
    - name: mullvad - download deb package
      get_url:
        url: https://mullvad.net/download/app/deb/latest
        dest: /tmp/mullvad-latest.deb
        checksum: sha256:ddebc807c216d1b8a846ab6901d0914210f2c2ef313cc375a3186a40620100d6
    - name: mullvad - install with apt
      apt:
        deb: /tmp/mullvad-latest.deb
      become: yes
    - name: mullvad - configure
      shell: |
        mullvad auto-connect set on
        mullvad lan set allow
        mullvad dns set default --block-ads --block-gambling --block-malware --block-trackers
