- name: "Setting up a VPN client."
  hosts: localhost
  connection: local
  tasks:
    # install VPN
    - name: mullvad - download deb package
      get_url:
        url: https://mullvad.net/download/app/deb/latest
        dest: /tmp/mullvad-latest.deb
        checksum: sha256:22113ddcd5d7f22c25beca3e7a2f706d5c8924bb648eb65ff2a078dc066b7bee
    - name: mullvad - install with apt
      apt:
        deb: /tmp/mullvad-latest.deb
      become: yes
    - name: mullvad - configure
      shell: |
        mullvad auto-connect set on
        mullvad lan set allow
        mullvad dns set default --block-ads --block-gambling --block-malware --block-trackers

    - name: ufw - deny all incoming
      ufw:
        rule: deny
        direction: incoming
        state: enabled
      become: yes
    - name: ufw - deny all routing
      ufw:
        rule: deny
        direction: routed
        state: enabled
      become: yes
    - name: ufw - allow all outgoing
      ufw:
        rule: allow
        direction: outgoing
        state: enabled
      become: yes
