- name: "Setting up a VPN client."
  hosts: localhost
  connection: local
  tasks:
    # install VPN
    - name: mullvad - download deb package
      get_url:
        url: https://mullvad.net/download/app/deb/latest
        dest: /tmp/mullvad-latest.deb
        checksum: sha256:22113ddcd5d7f22c25beca3e7a2f706d5c8924bb648eb65ff2a078dc066b7bee
    - name: mullvad - install with apt
      apt:
        deb: /tmp/mullvad-latest.deb
      become: yes
    - name: mullvad - configure
      shell: |
        mullvad auto-connect set on
        mullvad lan set allow
        mullvad dns set default --block-ads --block-gambling --block-malware --block-trackers
    - name: mullvad - create autostart directory
      file:
        path: ~/.config/autostart
        state: directory
    - name: mullvad - symlink autostart file
      file:
        src: "{{ playbook_dir }}/config/autostart/mullvad.desktop"
        dest: ~/.config/autostart/mullvad.desktop
        state: link
        force: true

    - name: firewall - deny all incoming
      ufw:
        rule: deny
        direction: in
        state: enabled
      become: yes

    - name: bluetooth - disable with systemd (to use it, run 'sudo systemctl start bluetooth.service')
      systemd:
        name: bluetooth.service
        state: stopped
        enabled: false
      become: yes
    - name: wifi - turn off on startup/login
      file:
        src: "{{ playbook_dir }}/config/autostart/wifi-off.desktop"
        dest: ~/.config/autostart/wifi-off.desktop
        state: link
        force: true
