- name: "Setting up a VPN client."
  hosts: localhost
  connection: local
  tasks:
    # install VPN
    - name: mullvad - download deb package
      get_url:
        url: https://mullvad.net/download/app/deb/latest
        dest: /tmp/mullvad-latest.deb
        checksum: sha256:f972bdc54792b3ddde826b6c43ba804ee83f9fdb5a79092673866039b3d8be7e
    - name: mullvad - install with apt
      apt:
        deb: /tmp/mullvad-latest.deb
      become: yes
    - name: mullvad - configure
      shell: |
        mullvad auto-connect set on
        mullvad lan set allow
        mullvad dns set default --block-ads --block-gambling --block-malware --block-trackers
